/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Pytest Collect Report
 */
export interface CollectReport {
  /**
   * The event type
   */
  event: "CollectReport"
  /**
   * The node id of the collector (if any)
   */
  node_id: string
  /**
   * The collected items
   */
  items: (TestDirectory | TestModule | TestSuite | TestCase)[]
  [k: string]: unknown
}
/**
 * Pytest Test Directory
 */
export interface TestDirectory {
  /**
   * Node ID
   */
  node_id: string
  /**
   * Node Type
   */
  node_type: "directory"
  /**
   * Test Name
   */
  name: string
  /**
   * Directory path
   */
  path: string
  [k: string]: unknown
}
/**
 * Pytest Test Module
 */
export interface TestModule {
  /**
   * Node ID
   */
  node_id: string
  /**
   * Node Type
   */
  node_type: "module"
  /**
   * Module name
   */
  name: string
  /**
   * File path
   */
  path: string
  /**
   * Module docstring
   */
  doc: string
  /**
   * Test markers
   */
  markers: string[]
  [k: string]: unknown
}
/**
 * Pytest Test Suite
 */
export interface TestSuite {
  /**
   * Node ID
   */
  node_id: string
  /**
   * Node Type
   */
  node_type: "suite"
  /**
   * Suite name
   */
  name: string
  /**
   * Module name
   */
  module: string
  /**
   * File path
   */
  path: string
  /**
   * Suite documentation
   */
  doc: string
  /**
   * Test markers
   */
  markers: string[]
  [k: string]: unknown
}
/**
 * Pytest Test Case
 */
export interface TestCase {
  /**
   * Node ID
   */
  node_id: string
  /**
   * Node Type
   */
  node_type: "case"
  /**
   * File path
   */
  path: string
  /**
   * Module name
   */
  module?: string
  /**
   * Parent suite
   */
  suite?: string
  /**
   * Function name
   */
  function?: string
  /**
   * Test Name
   */
  name: string
  /**
   * Test docstring
   */
  doc: string
  /**
   * Test markers
   */
  markers: string[]
  /**
   * Test parameters names and types
   */
  parameters: {
    [k: string]: string
  }
  [k: string]: unknown
}
