/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Pytest Discover Event
 */
export type DiscoveryEvent =
  | CollectReport
  | ErrorMessage
  | WarningMessage
  | SessionStart
  | SessionFinish

/**
 * Pytest Collect Report
 */
export interface CollectReport {
  /**
   * The event type
   */
  event: "CollectReport"
  /**
   * The node id of the collector (if any)
   */
  node_id?: string
  /**
   * The collected items
   */
  items: TestItem[]
  [k: string]: unknown
}
/**
 * Pytest Test Item
 */
export interface TestItem {
  /**
   * Node ID
   */
  node_id: string
  /**
   * File path
   */
  file?: string
  /**
   * Module name
   */
  module?: string
  /**
   * Class name
   */
  parent?: string
  /**
   * Function name
   */
  function?: string
  /**
   * Test Name
   */
  name: string
  /**
   * Test docstring
   */
  doc: string
  /**
   * Test markers
   */
  markers: string[]
  /**
   * Test parameters names and types
   */
  parameters: {
    [k: string]: string
  }
  [k: string]: unknown
}
/**
 * An error message
 */
export interface ErrorMessage {
  /**
   * The event type
   */
  event: "ErrorMessage"
  /**
   * When the error message is emitted
   */
  when: "config" | "collect" | "runtest"
  /**
   * The filename of the file where the error message is emitted
   */
  filename: string
  /**
   * The line number of the file where the error message is emitted
   */
  lineno: number
  /**
   * The exception type
   */
  exception_type: string
  /**
   * The exception value
   */
  exception_value: string
  [k: string]: unknown
}
/**
 * A warning message
 */
export interface WarningMessage {
  /**
   * The event type
   */
  event: "WarningMessage"
  /**
   * When the warning message is emitted
   */
  when: "config" | "collect" | "runtest"
  /**
   * The filename of the file where the warning message is emitted
   */
  filename: string
  /**
   * The line number of the file where the warning message is emitted
   */
  lineno: number
  /**
   * The category of the warning message
   */
  category?: string
  /**
   * The warning message
   */
  message: string
  [k: string]: unknown
}
/**
 * Pytest Session Start
 */
export interface SessionStart {
  /**
   * The event type
   */
  event: "SessionStart"
  /**
   * The version of pytest that is running the tests
   */
  pytest_version: string
  /**
   * The version of pytest-discover plugin that discovered the tests
   */
  plugin_version: string
  [k: string]: unknown
}
/**
 * Pytest Session Finish
 */
export interface SessionFinish {
  /**
   * The event type
   */
  event: "SessionFinish"
  /**
   * The status which pytest will return to the system
   */
  exit_status: number
  [k: string]: unknown
}
