/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An error message
 */
export interface ErrorMessage {
  /**
   * The event type
   */
  event: "ErrorMessage"
  /**
   * When the error message is emitted
   */
  when: "config" | "collect" | "runtest"
  location: Location
  /**
   * The exception type
   */
  exception_type: string
  /**
   * The exception value
   */
  exception_value: string
  traceback: Traceback
  [k: string]: unknown
}
/**
 * The location of the error
 */
export interface Location {
  /**
   * File name
   */
  filename: string
  /**
   * Line number
   */
  lineno: number
  [k: string]: unknown
}
/**
 * The traceback of the error
 */
export interface Traceback {
  /**
   * Traceback entries
   */
  lines: string[]
  [k: string]: unknown
}
