/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Location in code source
 */
export interface Location {
  /**
   * File name
   */
  filename: string
  /**
   * Line number
   */
  lineno: number
  [k: string]: unknown
}
