/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Pytest Session Start
 */
export interface SessionStart {
  /**
   * The event type
   */
  event: "SessionStart";
  /**
   * The version of pytest that is running the tests
   */
  pytest_version: string;
  /**
   * The version of pytest-discover plugin that discovered the tests
   */
  plugin_version: string;
  [k: string]: unknown;
}
