/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Pytest Session Finish
 */
export interface SessionFinish {
  /**
   * The event type
   */
  event: "SessionFinish";
  /**
   * The status which pytest will return to the system
   */
  exit_status: number;
  [k: string]: unknown;
}
