/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Pytest Test Suite
 */
export interface TestSuite {
  /**
   * Node ID
   */
  node_id: string
  /**
   * Node Type
   */
  node_type: "suite"
  /**
   * Suite name
   */
  name: string
  /**
   * Module name
   */
  module: string
  /**
   * File path
   */
  path: string
  /**
   * Suite documentation
   */
  doc: string
  /**
   * Test markers
   */
  markers: string[]
  [k: string]: unknown
}
