/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Pytest Test Directory
 */
export interface TestDirectory {
  /**
   * Node ID
   */
  node_id: string
  /**
   * Node Type
   */
  node_type: "directory"
  /**
   * Test Name
   */
  name: string
  /**
   * Directory path
   */
  path: string
  [k: string]: unknown
}
