/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Error traceback
 */
export interface Traceback {
  /**
   * Traceback entries
   */
  lines: string[]
  [k: string]: unknown
}
