/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A warning message
 */
export interface WarningMessage {
  /**
   * The event type
   */
  event: "WarningMessage";
  /**
   * When the warning message is emitted
   */
  when: "config" | "collect" | "runtest";
  /**
   * The filename of the file where the warning message is emitted
   */
  filename: string;
  /**
   * The line number of the file where the warning message is emitted
   */
  lineno: number;
  /**
   * The category of the warning message
   */
  category?: string;
  /**
   * The warning message
   */
  message: string;
  [k: string]: unknown;
}
