/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A warning message
 */
export interface WarningMessage {
  /**
   * The event type
   */
  event: "WarningMessage"
  /**
   * When the warning message is emitted
   */
  when: "config" | "collect" | "runtest"
  /**
   * The node ID of the node where the warning message is emitted
   */
  node_id: string
  location: Location
  /**
   * The warning message
   */
  message: string
  /**
   * The category of the warning message
   */
  category?: string
  [k: string]: unknown
}
/**
 * Location in code source
 */
export interface Location {
  /**
   * File name
   */
  filename: string
  /**
   * Line number
   */
  lineno: number
  [k: string]: unknown
}
