# generated by datamodel-codegen:
#   filename:  collect_report.json

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Union

from . import test_case, test_directory, test_module, test_suite


@dataclass
class CollectReport:
    """
    A report of collected items.
    """

    node_id: str
    """
    The node id of the node for which items were collected (the top level root directory has an empty node id).
    """
    items: List[
        Union[
            test_directory.TestDirectory,
            test_module.TestModule,
            test_suite.TestSuite,
            test_case.TestCase,
        ]
    ]
    """
    The collected items.
    """
    event: str = "CollectReport"
    """
    The event type. Always 'CollectReport'.
    """
