# generated by datamodel-codegen:
#   filename:  collect_report.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional


@dataclass
class CollectReport:
    """
    Pytest Collect Report
    """

    name: str
    """
    Test Name
    """
    doc: str
    """
    Test docstring
    """
    markers: List[str]
    """
    Test markers
    """
    parameters: Dict[str, str]
    """
    Test parameters
    """
    event: str = "CollectReport"
    node_id: Optional[str] = None
    """
    Node ID
    """
    module: Optional[str] = None
    """
    Module name
    """
    parent: Optional[str] = None
    """
    Class name
    """
    function: Optional[str] = None
    """
    Function name
    """
    file: Optional[str] = None
    """
    File path
    """
