# generated by datamodel-codegen:
#   filename:  location.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass
class Location:
    """
    Location in code source
    """

    filename: str
    """
    File name
    """
    lineno: int
    """
    Line number
    """
    function: Optional[str] = None
    """
    Function name
    """
