# generated by datamodel-codegen:
#   filename:  session_start.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class SessionStart:
    """
    Pytest Session Start
    """

    pytest_version: str
    """
    The version of pytest that is running the tests
    """
    event: str = "SessionStart"
    """
    The event type
    """
