# generated by datamodel-codegen:
#   filename:  test_module.json

from __future__ import annotations

from dataclasses import dataclass
from typing import List


@dataclass
class TestModule:
    """
    Pytest Test Module
    """

    node_id: str
    """
    Node ID
    """
    name: str
    """
    Module name
    """
    path: str
    """
    File path
    """
    doc: str
    """
    Module docstring
    """
    markers: List[str]
    """
    Test markers
    """
    node_type: str = "module"
    """
    Node Type
    """
