# generated by datamodel-codegen:
#   filename:  test_case_finished.json

from __future__ import annotations

from dataclasses import dataclass

from . import outcome


@dataclass
class TestCaseFinished:
    """
    Pytest Test Case Finished
    """

    node_id: str
    """
    Node ID
    """
    outcome: outcome.Outcome
    duration: float
    """
    Duration in seconds
    """
    start: str
    """
    Start time
    """
    stop: str
    """
    Stop time
    """
    event_type: str = "case_finished"
    """
    Event Type
    """
