# generated by datamodel-codegen:
#   filename:  test_case_report.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from . import (
    outcome,
    test_case_call,
    test_case_finished,
    test_case_setup,
    test_case_teardown,
)


@dataclass
class TestCaseReport:
    """
    Pytest Test Case Report
    """

    node_id: str
    """
    Node ID
    """
    outcome: outcome.Outcome
    setup: test_case_setup.TestCaseSetup
    finished: test_case_finished.TestCaseFinished
    call: Optional[test_case_call.TestCaseCall] = None
    teardown: Optional[test_case_teardown.TestCaseTeardown] = None
