# generated by datamodel-codegen:
#   filename:  test_case_error.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from . import traceback


@dataclass
class TestCaseError:
    """
    Pytest Test Case Error
    """

    message: str
    """
    Error message
    """
    traceback: Optional[traceback.Traceback] = None
