# generated by datamodel-codegen:
#   filename:  test_case_call.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class TestCaseCall:
    """
    Pytest Test Case Call
    """

    node_id: str
    """
    Node ID
    """
    event_type: str = "call"
    """
    Event Type
    """
