# generated by datamodel-codegen:
#   filename:  test_case_outcome.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class TestCaseOutcome:
    """
    Pytest Test Case Outcome
    """

    node_id: str
    """
    Node ID
    """
    event_type: str = "outcome"
    """
    Event Type
    """
