# generated by datamodel-codegen:
#   filename:  test_case_setup.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from . import outcome, test_case_error


@dataclass
class TestCaseSetup:
    """
    Pytest Test Case Setup
    """

    node_id: str
    """
    Node ID
    """
    outcome: outcome.Outcome
    duration: float
    """
    Duration in seconds
    """
    event_type: str = "case_setup"
    """
    Event Type
    """
    error: Optional[test_case_error.TestCaseError] = None
