# generated by datamodel-codegen:
#   filename:  test_case_setup.json

from __future__ import annotations

from dataclasses import dataclass

from . import outcome


@dataclass
class TestCaseSetup:
    """
    Pytest Test Case Setup
    """

    node_id: str
    """
    Node ID
    """
    outcome: outcome.Outcome
    event_type: str = "case_setup"
    """
    Event Type
    """
