# generated by datamodel-codegen:
#   filename:  test_case_setup.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class TestCaseSetup:
    """
    Pytest Test Case Setup
    """

    node_id: str
    """
    Node ID
    """
    event_type: str = "setup"
    """
    Event Type
    """
