# generated by datamodel-codegen:
#   filename:  test_suite.json

from __future__ import annotations

from dataclasses import dataclass
from typing import List


@dataclass
class TestSuite:
    """
    Pytest Test Suite
    """

    node_id: str
    """
    Node ID
    """
    name: str
    """
    Suite name
    """
    module: str
    """
    Module name
    """
    path: str
    """
    File path
    """
    doc: str
    """
    Suite documentation
    """
    markers: List[str]
    """
    Test markers
    """
    node_type: str = "suite"
    """
    Node Type
    """
