# generated by datamodel-codegen:
#   filename:  test_directory.json

from __future__ import annotations

from dataclasses import dataclass
from typing import List


@dataclass
class TestDirectory:
    """
    Pytest Test Directory
    """

    node_id: str
    """
    Node ID
    """
    name: str
    """
    Test Name
    """
    path: str
    """
    Directory path
    """
    markers: List[str]
    """
    Test markers
    """
    node_type: str = "directory"
    """
    Node Type
    """
