# generated by datamodel-codegen:
#   filename:  traceback.json

from __future__ import annotations

from dataclasses import dataclass
from typing import List


@dataclass
class Traceback:
    """
    Error traceback
    """

    lines: List[str]
    """
    Traceback entries
    """
